HakatonApp.Web/Areas/Quests/Models/ApproveQuestFormModel.cs
namespace HakatonApp.Web.Areas.Quests.Models
{
    public class ApproveQuestFormModel
    {
        public int NumOfParticipants { get; set; }

        public int PointsPerPerson { get; set; }
    }
}

HakatonApp.Web/Areas/Quests/Models/QuestCreateFormModel.cs
namespace HakatonApp.Web.Areas.Quests.Models
{
    using Microsoft.AspNetCore.Http;
    using System;
    using System.Collections.Generic;

    public class QuestCreateFormModel
    {
        public string Name { get; set; }

        public string Description { get; set; }

        public int StatusId { get; set; }

        public DateTime DateOfQuest { get; set; }

        public IFormFile Image { get; set; } 
    }
}

HakatonApp.Web/Areas/Quests/Controllers/QuestController.cs
namespace HakatonApp.Web.Areas.Quests.Controllers
{
    using HakatonApp.Common;
    using HakatonApp.Services;
    using HakatonApp.Services.Vauchers;
    using HakatonApp.Web.Areas.Quests.Models;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using static HakatonApp.Common.GlobalConstants;

    [Area("Quests")]
    public class QuestController : Controller
    {
        private readonly IQuestService questService;
        private readonly ISanitizerService sanitizerService;
        private readonly IImageService imageService;
        private readonly IVaucherService voucherService;

        public QuestController(IQuestService questService, ISanitizerService sanitizerService, IImageService imageService, IVaucherService voucherService)
        {
            this.voucherService = voucherService;
            this.questService = questService;
            this.sanitizerService = sanitizerService;
            this.imageService = imageService;
        }

        [Authorize]
        [Route("/Quest/Add")]
        [HttpPost]
        public IActionResult Add(QuestCreateFormModel quest)
        {
            var description = this.sanitizerService.Sanitize(quest.Description);
            var result = this.questService.CreateQuest(quest.Name, description, quest.StatusId, quest.DateOfQuest, quest.Image);

            if (result)
            {
                TempData["succesInfo"] = "Вие успешно добавихте инициатива!";
            }
            else
            {
                TempData["dangerInfo"] = "Възникна проблем! Опитайте отново!";
            }

            return Redirect("/Home/Index");
        }

        [Authorize]
        [Route("/Quest/Add")]
        [HttpGet]
        public IActionResult Add()
            => View(new QuestCreateFormModel());

        [Authorize(Roles = RoleAdmin + ", " + RoleEditor)]
        [Route("/Quest/Upadate/{id}")]
        [HttpPost]
        public IActionResult Update(QuestCreateFormModel quest, int id)
        {
            var description = this.sanitizerService.Sanitize(quest.Description);
            var oldQuest = this.questService.GetQuestById(id);

            oldQuest.Name = quest.Name;
            oldQuest.Description = description;
            this.questService.UpdateQuest(id, quest.Name, description, quest.StatusId);
            
            return null;
        }

        [Authorize(Roles = RoleAdmin + ", " + RoleEditor)]
        [Route("/Quest/Upadate/{id}")]
        [HttpGet]
        public IActionResult Update(int id)
            => View(this.questService.GetQuestById(id));

        [Authorize(Roles = RoleAdmin + ", " + RoleEditor)]
        [Route("/Quest/Approve/{id}")]
        [HttpGet]
        public IActionResult ApproveQuest()
            => View(new ApproveQuestFormModel());

        [Authorize(Roles = RoleAdmin + ", " + RoleEditor)]
        [Route("/Quest/Approve/{id}")]
        [HttpPost]
        public IActionResult ApproveQuest(int id, ApproveQuestFormModel model)
        {
            var result = this.questService.ApproveQuest(id, model.NumOfParticipants, model.PointsPerPerson);

            if (result)
            {
                this.voucherService.GenerateVauchers(id);
                TempData["succesInfo"] = "Вие успешно одобрихте инициатива!";
            }
            else
            {
                TempData["dangerInfo"] = "Възникна проблем! Опитайте отново!";
            }


            return Redirect("/Home/Index");
        }

        [Route("/Quest/Today/Approved")]
        public IActionResult TodayApprovedQuests()
            => View(this.questService.getTodayApprovedQuests());

        [Route("/Quest/Approved")]
        public IActionResult GetAllApproved()
            => View(this.questService.getApprovedQuests());

        [Route("/Quest/Waiting")]
        public IActionResult GetAllQuestsInProcess()
            => View(this.questService.getProcessingQuests());

        [Route("/Quest/All")]   
        public IActionResult GetAllQuests()
            => View(this.questService.getAllQuests());
        
        [Route("/Quest/{id}")]
        public IActionResult GetById(int id)
            => View(this.questService.GetQuestById(id));

        [Route("/Quest/Like/{id}")]
        [HttpPost]
        public IActionResult LikeQuest(int id)
        {
            this.questService.LikeQuest(id);
            
            TempData["succesInfo"] = "Вие успешно подкрепихте инициатива!";
            return Redirect("/Home/Index");
        }
    }
}

HakatonApp.Web/Areas/Vouchers/Controllers/VoucherController.cs
namespace HakatonApp.Web.Areas.Vouchers.Controllers
{
    using HakatonApp.Services.Users;
    using HakatonApp.Services.Vauchers;
    using HakatonApp.Web.Areas.Vouchers.Models;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity.UI.Services;
    using Microsoft.AspNetCore.Mvc;
    using System.Linq;
    using static HakatonApp.Common.GlobalConstants;
    
    [Area("Vouchers")]
    public class VoucherController: Controller
    {
        private readonly IVaucherService voucherService;
        private readonly IEmailSender emailSender;
        private readonly IUserService userService;

        public VoucherController(IVaucherService voucherService, IEmailSender emailSender)
        {
            this.emailSender = emailSender;
            this.voucherService = voucherService;
        }
        
        [Authorize(Roles = RoleAdmin + ", " + RoleEditor)]
        [HttpGet]
        [Route("/Vouchers/Generate")]
        public IActionResult Generate(int questId)
        {
            var codes = this.voucherService.GetCodes(questId);

            return View(codes);
        }

        [Authorize]
        [HttpGet]
        [Route("/Vouchers/Use")]
        public IActionResult Use()
            => View();
        
        [Authorize]
        [HttpPost]
        [Route("/Vouchers/Use")]
        public IActionResult Use(CodeFormModel model)
        {
            var result = this.voucherService.UseVoucher(model.Code);

            if (result)
            {
                TempData["succesInfo"] = "Успешно добавихте точки към профила си!";
            }
            else
            {
                TempData["dangerInfo"] = "Успешно добавихте точки към профила си!";
            }
            
            return Redirect("/Home/Index");
        }

        [Authorize(Roles = RoleAdmin + ", " + RoleEditor)]
        [Route("/Voucher/Send/{questId}")]
        [HttpGet]
        public IActionResult SendVoucher()
            => View(new EmailFormModel());

        [Authorize(Roles = RoleAdmin + ", " + RoleEditor)]
        [Route("/Voucher/Send/{questId}")]
        [HttpPost]
        public IActionResult SendVoucher(EmailFormModel model, int questId)
        {
            var vaucher = this.voucherService.GetCodes(questId).FirstOrDefault();

            if (vaucher != null)
            {
                this.emailSender.SendEmailAsync(model.Email, "Код за точки", "Здравейте, това е вашият код: " + vaucher);
            }

            TempData["succesInfo"] = "Успешно изпратихте съобщението!";

            return Redirect("/Home/Index");
        }
    }
}

HakatonApp.Web/Areas/Quests/Views/Quest/Add.cshtml
@model QuestCreateFormModel
@{
    ViewData["Title"] = "Add";
}

<div class="container">
    <form asp-area="Quests" enctype="multipart/form-data" asp-controller="Quest" asp-action="Add" method="post">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name">Име</label>
            <input asp-for="Name" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="Description">Описание</label>
            <input id="description" asp-for="Description" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="DateOfQuest">Дата на инициативата</label>
            <input id="description" asp-for="DateOfQuest" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="Image">Снимка</label>
            <input type="file" asp-for="Image">
        </div>
        <img src="#" id="img" hidden />
        <button type="submit" class="btn btn-default">Изпрати</button>
    </form>
</div>

@section Scripts{
    <script src='https://cloud.tinymce.com/stable/tinymce.min.js'></script>
    <script>
        tinymce.init({
            selector: '#description'
        });
    </script>
}

HakatonApp.Web/Areas/Quests/Views/Quest/ApproveQuest.cshtml
@model ApproveQuestFormModel
@{
    ViewData["Title"] = "ApproveQuest";
}

<div class="container">
    <form asp-area="Quests" enctype="multipart/form-data" asp-controller="Quest" asp-action="Add" method="post">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="NumOfParticipants">Необходими доброволци</label>
            <input asp-for="NumOfParticipants" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="PointsPerPerson">Точки за човек</label>
            <input id="description" asp-for="PointsPerPerson" class="form-control">
        </div>
        <button type="submit" class="btn btn-default">Изпрати</button>
    </form>
</div>

HakatonApp.Web/Areas/Quests/Views/Quest/GetAllApproved.cshtml
@model IEnumerable<QuestServiceModel>
@{
    ViewData["Title"] = "All";
}


@foreach (var quest in Model)
{


    <div class="col-lg-3 col-md-5 mb-4">
        <div class="card h-100">
            @{
                if (quest.Image != null)
                {
                    var base64 = Convert.ToBase64String(quest.Image);
                    var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                    <a href="#"><img class="card-img-top" style="height: 250px;" src="@imgSrc" alt=""></a>
                }
            }
            <div class="card-body">
                <h4 class="card-title">
                    <a href="#">@quest.Name</a>
                </h4>
                <p class="card-text">@Html.Raw(quest.Description)</p>
                <div class="py-3">
                    @{ var data = new Dictionary<string, string>() { { "id", quest.Id.ToString() } }; }
                    <a asp-area="Quests" asp-controller="Quest" asp-action="GetById" asp-all-route-data="data" class="btn btn-success float-right">Още</a>
                </div>
            </div>
        </div>
    </div>
}

HakatonApp.Web/Areas/Quests/Views/Quest/GetAllQuests.cshtml
@model IEnumerable<QuestServiceModel>
@{
    ViewData["Title"] = "All";
}


@foreach (var quest in Model)
{


    <div class="col-lg-3 col-md-5 mb-4">
        <div class="card h-100">
            @{
                if (quest.Image != null)
                {
                    var base64 = Convert.ToBase64String(quest.Image);
                    var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                    <a href="#"><img class="card-img-top" style="height: 250px;" src="@imgSrc" alt=""></a>
                }
            }
            <div class="card-body">
                <h4 class="card-title">
                    <a href="#">@quest.Name</a>
                </h4>
                <p class="card-text text-nowrap">@Html.Raw(quest.Description)</p>
                <div class="py-3">
                    @{ var data = new Dictionary<string, string>() { { "id", quest.Id.ToString() } }; }
                    <a asp-area="Quests" asp-controller="Quest" asp-action="GetById" asp-all-route-data="data" class="btn btn-success float-right">Още</a>
                </div>
            </div>
        </div>
    </div>
}

HakatonApp.Web/Areas/Quests/Views/Quest/GetAllQuestsInProcess.cshtml
@model IEnumerable<QuestServiceModel>
@{
    ViewData["Title"] = "All";
}


@foreach (var quest in Model)
{


    <div class="col-lg-3 col-md-5 mb-4">
        <div class="card h-100">
            @{
                if (quest.Image != null)
                {
                    var base64 = Convert.ToBase64String(quest.Image);
                    var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                    <a href="#"><img class="card-img-top" style="height: 250px;" src="@imgSrc" alt=""></a>
                }
            }
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="#">@quest.Name</a>
                    </h4>
                    <p class="card-text">@Html.Raw(quest.Description)</p>
                    <div class="py-3">
                        @{ var data = new Dictionary<string, string>() { { "id", quest.Id.ToString() } }; }
                        <a asp-area="Quests" asp-controller="Quest" asp-action="GetById" asp-all-route-data="data" class="btn btn-success float-right">Още</a>
                    </div>
                </div>
        </div>
    </div>
}

HakatonApp.Web/Areas/Quests/Views/Quest/GetById.cshtml
@model QuestServiceModel
@{
    ViewData["Title"] = "All";
}

<div class="container jumbotron my-4">
    <div class="row center-block">
        <div class="">
            <h4 class="text-center">
                @Model.Name
            </h4>
            @{
                if (Model.Image != null)
                {
                    var base64 = Convert.ToBase64String(Model.Image);
                    var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                    <img class="center-block" style="height: 300px; width: 400px;" src="@imgSrc" alt="">
                }
            }
            <div class="text-center">
                @Html.Raw(Model.Description)
            </div>
            <div class="text-center">
                <h4>Дата на провежадане: </h4><p>@Model.DateOfQuest</p>
            </div>
            <div class="text-center">
                <h4>Брой харесвания: </h4><p>@Model.NumOfLikes</p>
            </div>
            @if (User.IsInRole("Admin"))
            {
                <div class="text-center">
                    @{ var data = new Dictionary<string, string>() { { "id", Model.Id.ToString() } }; }
                    <a asp-area="Vouchers" asp-controller="Voucher" asp-action="SendVoucher" asp-all-route-data="data" class="btn btn-success float-right">Изпрати ваучер</a>
                </div>
            }
            else
            {
                <div class="text-center">
                    @{ var data = new Dictionary<string, string>() { { "id", Model.Id.ToString() } }; }
                    <form action="/Quest/Like/@(Model.Id)" @*asp-area="Quests" asp-controller="Quest" asp-action="LikedQuest" asp-all-route-data="data"*@ method="post">
                        <input type="submit" value="Харесай" class="btn btn-success" />
                    </form>
                </div>
            }
        </div>
    </div>
</div>

HakatonApp.Web/Areas/Quests/Views/Quest/TodayApprovedQuests.cshtml
@model IEnumerable<QuestServiceModel>
@{
    ViewData["Title"] = "All";
}


@foreach (var quest in Model)
{
    <div class="col-lg-3 col-md-5 mb-4">
        <div class="card h-100">
            @{
                if (quest.Image != null)
                {
                    var base64 = Convert.ToBase64String(quest.Image);
                    var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                    <a href="#"><img class="card-img-top" style="height: 250px;" src="@imgSrc" alt=""></a>
                }
            }
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="#">@quest.Name</a>
                    </h4>
                    <p class="card-text">@Html.Raw(quest.Description)</p>
                    <div class="py-3">
                        @{ var data = new Dictionary<string, string>() { { "id", quest.Id.ToString() } }; }
                        <a asp-area="Quests" asp-controller="Quest" asp-action="GetById" asp-all-route-data="data" class="btn btn-success float-right">Още</a>
                    </div>
                </div>
        </div>
    </div>
}